[package]
name = "benches"
version = "0.1.0"
authors = [
    "Bevy Contributors <bevyengine@gmail.com>",
    "Carter Anderson <mcanders1@gmail.com>",
]
edition = "2018"

[dev-dependencies]
criterion = "0.3"
rand = { version = "0.8.0", features = ["small_rng"] }
bevy = { path = "../" }

[[bench]]
name = "system_stage"
path = "benches/bevy_ecs/stages.rs"
harness = false

[[bench]]
name = "commands"
path = "benches/bevy_ecs/commands.rs"
harness = false

[[bench]]
name = "iter"
path = "benches/bevy_tasks/iter.rs"
harness = false
